version: '3.9'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    restart: always
    environment:
      - PORT=${PORT}
    networks:
      - my-net
    volumes:
    - data:/usr/app/data
  postgres:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - my-net
networks:
  my-net:
    driver: bridge

volumes:
  data:

