version: '3.1'

services:
  node:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      - PORT=4000
  postgres:
    build: .
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
