version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    restart: always
    environment:
      - PORT=${PORT}
    networks:
      - home-library
  postgres:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - home-library
networks:
  home-library:
    driver: bridge
volumes:
  postgres-data:
  node-modules:
